version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./database:/app/database
      - ./reports:/app/reports
      - ./templates:/app/templates
      - ./backend/cache/huggingface:/app/cache/huggingface
    environment:
      - FLASK_ENV=production
      - DEBUG=False
    restart: always
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
